aatorgar/urls.py
from django.contrib import admin

from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static


from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('viewpage.urls')),
    path('biblioteca/', include('biblioteca.urls'))
]


urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT})
]

viewpage/urls.py
from django.urls import path
from .views import inicio,quienes_somos,galeriaView, comision_directiva, ActividadesView, ProfesionalesView, FormacionView, GuiasFolletosView,SociosSuscriptoresView, PreguntasFrecuentesView, contactView,successView,donar


urlpatterns = [
    path('', inicio.as_view(), name= 'inicio' ),
    path('quienes-somos/', quienes_somos.as_view(), name="quienes-somos"),
    path('comision-directiva/', comision_directiva.as_view(), name="comision-directiva"),
    path('galeria/', galeriaView.as_view(), name="galeria"),
    path('actividades/', ActividadesView.as_view(), name="actividades"),
    path('profesionales/', ProfesionalesView.as_view(), name="profesionales"),
    path('formacion/', FormacionView.as_view(), name="formacion"),
    path('guias-folletos/', GuiasFolletosView.as_view(), name="guias-folletos"),
    path('socios-suscriptores/', SociosSuscriptoresView, name="socios-suscriptores"),
    path('preguntas-frecuentes/', PreguntasFrecuentesView.as_view(), name="preguntas-frecuentes"),
    path('contacto/', contactView, name="contacto"),
    path('success/', successView, name="success"),
    path('donar/', donar, name="donar"),

]

viewpage/models.py
from django.db import models
from .listas import paises, provincias, tipopersona


# Create your models here.

class SociosSuscriptoresModel(models.Model):
    Socio_suscriptor=models.CharField(max_length=100,choices=(('Suscriptor', 'Suscriptor'), ('Socio', 'Socio')), default="Suscriptor")
    nombre=models.CharField(max_length=100)
    apellido=models.CharField(max_length=100)
    mail=models.EmailField(max_length=100)
    telefono=models.CharField(max_length=100)
    pais=models.CharField(max_length=100,choices=paises, default="Argentina")
    provincia=models.CharField(max_length=100,choices=provincias, default="CABA")
    lugar_de_residencia=models.CharField(max_length=100)
    nacimiento=models.DateField()
    tipo_de_persona=models.CharField(max_length=100,choices=tipopersona, default="Socio persona que tartamudea")
    mensaje=models.TextField(blank=True, null=True)

    def __str__(self):
        return self.nombre


class ContactoModel(models.Model):
    nombre=models.CharField(max_length=100)
    mail=models.EmailField(max_length=100)
    mensaje=models.TextField()

    def __str__(self):
        return "Consulta de " + self.nombre
    

viewpage/forms.py
from django import forms
from .models import SociosSuscriptoresModel, ContactoModel

class DateInput(forms.DateInput):
    input_type = 'date'

class SociosSuscriptoresForm(forms.ModelForm):
    
    
    class Meta:
        model = SociosSuscriptoresModel
        fields = '__all__'
        widgets = {
            'nacimiento': DateInput()
        }


    def __init__(self, *args, **kwargs):
        super(SociosSuscriptoresForm, self).__init__(*args, **kwargs)

        # for example change class for integerPolje1
        self.fields['nombre'].widget.attrs['class'] = 'input'
        self.fields['apellido'].widget.attrs['class'] = 'input'
        self.fields['mail'].widget.attrs['class'] = 'input'
        self.fields['telefono'].widget.attrs['class'] = 'input'
        self.fields['nacimiento'].widget.attrs['class'] = 'input'
        self.fields['lugar_de_residencia'].widget.attrs['class'] = 'input'
        self.fields['mensaje'].widget.attrs['class'] = 'textarea'
        
        #self.fields['pais'].widget = TextInput(attrs={
         #   'id': 'pais'})
            
        #self.fields['provincia'].widget = TextInput(attrs={
         #   'id': 'provincia'
            
        #})


    

    



class ContactoForm(forms.ModelForm):
    class Meta:
        model= ContactoModel
        fields = '__all__'


    def __init__(self, *args, **kwargs):
        super(ContactoForm, self).__init__(*args, **kwargs)

        # for example change class for integerPolje1
        self.fields['nombre'].widget.attrs['class'] = 'input'
        self.fields['mail'].widget.attrs['class'] = 'input'

        self.fields['mensaje'].widget.attrs['class'] = 'textarea'
        



    

viewpage/views.py
import json
import urllib.request
import smtplib

from django.shortcuts import render,redirect,HttpResponse
from django.views.generic import TemplateView, ListView, CreateView
from django.conf import settings
from django.contrib import messages


from .forms import SociosSuscriptoresForm, ContactoForm
from .models import SociosSuscriptoresModel

from email.mime.text import MIMEText
from email.header import Header



# Create your views here.

class inicio(TemplateView):
    template_name='inicio.html'


class quienes_somos(TemplateView):
    template_name='nosotros/quienes-somos.html'

class comision_directiva(TemplateView):
    template_name='nosotros/comision-directiva.html'

class galeriaView(TemplateView):
    template_name='nosotros/galeria.html'


class ActividadesView(TemplateView):
    template_name='tartamudez/Actividades.html'   

class ProfesionalesView(TemplateView):
    template_name='tartamudez/profesionales.html'



class FormacionView(TemplateView):
    template_name='tartamudez/Formacion.html'
    

class GuiasFolletosView(TemplateView):
    template_name='tartamudez/guias-folletos.html'

class PreguntasFrecuentesView(TemplateView):
    template_name='tartamudez/preguntas-frecuentes.html'


def SociosSuscriptoresView(request):
    form = SociosSuscriptoresForm(request.POST or None)
    if form.is_valid():
        
        recaptcha_response = request.POST.get('g-recaptcha-response')
        url = 'https://www.google.com/recaptcha/api/siteverify'
        recaptcha_response = request.POST.get('g-recaptcha-response')
        url = 'https://www.google.com/recaptcha/api/siteverify'
        values = {
            'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY, 'response': recaptcha_response
        }
        data = urllib.parse.urlencode(values).encode()
        req =  urllib.request.Request(url, data=data)
        response = urllib.request.urlopen(req)
        result = json.loads(response.read().decode())
        
        if result['success']:
            form.save()
            server = smtplib.SMTP("smtp.aat.org.ar", 587)#port
            server.ehlo()
            server.starttls()
            server.login()
            body = "Nombre: " + request.POST["nombre"] + "\n" + "apellido: " + request.POST["apellido"] + "\n" + "mail: " + request.POST["mail"] + "\n" + "telefono: " + request.POST["telefono"] + "\n" + "pais: " + request.POST["pais"] + "\n" + "provincia: " + request.POST["provincia"] + "\n" + "lugar de residencia: " + request.POST["lugar_de_residencia"] + "\n" + "nacimiento: " + request.POST["nacimiento"] + "\n" + "tipo de persona: " + request.POST["tipo_de_persona"] + "\n" + "mensaje: " + request.POST["mensaje"]
            msg = MIMEText(body,'plain','utf-8')
            subject = "Felicidades! Nuevo " + request.POST["Socio_suscriptor"]
            msg["Subject"] = Header(subject, 'utf-8')
            From = 'mensajeria@aat.org.ar'
            to = 'info@aat.org.ar'
            msg["From"] = Header(From, 'utf-8')
            msg["To"] = Header(to, 'utf-8')
            txt = msg.as_string()
            
            server.sendmail(From, to, txt)
            return redirect('success')
        else:
            messages.error(request, 'reCAPTCHA invalido, completelo de nuevo')
            #return redirect('socios-suscriptores')
        
       
            
        
        
            
    
        

    context = {
        'form':form
    }

    return render(request, "socios-suscriptores.html", context)

def contactView(request):
    form = ContactoForm(request.POST or None)
    
   

    if form.is_valid():
        
        recaptcha_response = request.POST.get('g-recaptcha-response')
        url = 'https://www.google.com/recaptcha/api/siteverify'
        recaptcha_response = request.POST.get('g-recaptcha-response')
        url = 'https://www.google.com/recaptcha/api/siteverify'
        values = {
            'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY, 'response': recaptcha_response
        }
        data = urllib.parse.urlencode(values).encode()
        req =  urllib.request.Request(url, data=data)
        response = urllib.request.urlopen(req)
        result = json.loads(response.read().decode())
        
        if result['success']:
            form.save()
            server = smtplib.SMTP("smtp.aat.org.ar", 587)#port
            server.ehlo()
            server.starttls()
            server.login()
            body = "Recibimos una consulta de parte de " + request.POST['nombre'] + " su mail de contacto es " + request.POST['mail'] + "\n Y su mensaje es: " + request.POST['mensaje'] 
            msg = MIMEText(body,'plain','utf-8')
            subject = "Nueva consulta de parte de "+  request.POST['nombre']
            msg["Subject"] = Header(subject, 'utf-8')
            From = 'mensajeria@aat.org.ar'
            to = 'info@aat.org.ar'
            msg["From"] = Header(From, 'utf-8')
            msg["To"] = Header(to, 'utf-8')
            txt = msg.as_string()
            server.sendmail(From, to, txt)
            return redirect('success')
        else:
            messages.error(request, 'reCAPTCHA invalido, completelo de nuevo')
            #return redirect('contacto')
        
        #form.save()
        
        
        
        
    context = {
        'form':form
    }
    return render(request, "contacto.html", context)

def successView(request):
    return render(request, "success.html")


def donar(request):
    
    form = ContactoForm(request.POST or None)
    if form.is_valid():
        
        recaptcha_response = request.POST.get('g-recaptcha-response')
        url = 'https://www.google.com/recaptcha/api/siteverify'
        recaptcha_response = request.POST.get('g-recaptcha-response')
        url = 'https://www.google.com/recaptcha/api/siteverify'
        values = {
            'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY, 'response': recaptcha_response
        }
        data = urllib.parse.urlencode(values).encode()
        req =  urllib.request.Request(url, data=data)
        response = urllib.request.urlopen(req)
        result = json.loads(response.read().decode())
        
        
        if result['success']:
            form.save()
            server = smtplib.SMTP("smtp.aat.org.ar", 587)#port
            server.ehlo()
            server.starttls()
            server.login()
            body = "Recibimos un mensaje de donacion de parte de " + request.POST['nombre'] + " su mail de contacto es " + request.POST['mail'] + "\n Y su mensaje es: " + request.POST['mensaje'] 
            recipient_list=["nahuelbarreiro@gmail.com"]
            msg = MIMEText(body,'plain','utf-8')
            subject = "Nuevo mensaje de donacion de parte de "+  request.POST['nombre']
            msg["Subject"] = Header(subject, 'utf-8')
            From = 'mensajeria@aat.org.ar'
            to = 'info@aat.org.ar'
            msg["From"] = Header(From, 'utf-8')
            msg["To"] = Header(to, 'utf-8')
            txt = msg.as_string()
            
            server.sendmail(From, to, txt)
            return redirect('success')
        else:
            messages.error(request, 'reCAPTCHA invalido, completelo de nuevo')
            #return redirect('donar')
        
        
        
        
    return render(request, "donar.html", {'form': form})

viewpage/templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="es">

<head>

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/tortuga.png' %}" />

  <link rel="stylesheet" href="{% static 'css/bulma.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  {% block galeria %}
  {% endblock galeria %}

  {% block js %}
  {% endblock js %}

  <title>{% block titulo %}{% endblock titulo %}</title>
  
  <script src='https://www.google.com/recaptcha/api.js'></script>







</head>

<body>
  {% comment %} navbar {% endcomment %}
  <section class="section" style="margin:0;
    padding: 0;">
    <nav class="navbar is-fixed-top is-spaced is-transparent border-bottom" role="navigation"
      aria-label="main navigation">
      <div class="navbar-brand">

        <img id='logo' src="{% static 'images/logo-aat.png' %}">

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
          data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-end">
          <a class="navbar-item" href={% url 'inicio' %}>
            Inicio
          </a>

          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              Nosotros
            </a>

            <div class="navbar-dropdown">
              <a class="navbar-item" href="{% url 'quienes-somos' %}">
                Quiénes somos
              </a>
              <a class="navbar-item" href="{% url 'comision-directiva' %}">
                Comisión directiva
              </a>
              <a class="navbar-item" href="{% url 'galeria' %}">
                Galeria
              </a>


            </div>
          </div>
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              Tartamudez
            </a>

            <div class="navbar-dropdown">
              <a class="navbar-item" href="{% url 'actividades' %}">
                Actividades
              </a>
              <a class="navbar-item" href="{% url 'profesionales' %}">
                Profesionales
              </a>
              <a class="navbar-item" href="{% url 'formacion' %}">
                Formación
              </a>
              <a class="navbar-item" href="{% url 'guias-folletos' %}">
                Guías y folletos
              </a>
              <a class="navbar-item" href="{% url 'Inicio_biblioteca' %}">
                Biblioteca
              </a>
              <a class="navbar-item" href="{% url 'socios-suscriptores' %}">
                Socios/Suscriptores
                </a>
              <a class="navbar-item" href="{% url 'preguntas-frecuentes' %}">
                Preguntas frecuentes
              </a>
            </div>
          </div>
          
          <a class="navbar-item" href="{% url 'contacto' %}">
            Contacto
          </a>
          <a class="button is-medium is-success is-outlined" id="donar" href="{% url 'donar' %}">
            Donar
          </a>
        </div>
      </div>
      </div>
      <script>
      document.addEventListener('DOMContentLoaded', () => {

  // Get all "navbar-burger" elements
  const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

  // Check if there are any navbar burgers
  if ($navbarBurgers.length > 0) {

    // Add a click event on each of them
    $navbarBurgers.forEach( el => {
      el.addEventListener('click', () => {

        // Get the target from the "data-target" attribute
        const target = el.dataset.target;
        const $target = document.getElementById(target);

        // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
        el.classList.toggle('is-active');
        $target.classList.toggle('is-active');

      });
    });
  }

});
</script>
    </nav>
  </section>

  {% block body %}{% endblock body %}



  {% comment %}
  <!-------------Footer-----------------------> {% endcomment %}


  <footer class="footer" style="background-color:#222222;">
    <div class="container">
      <div class="columns">
        <div class="column is-two-fifths is-hidden-mobile">
          <span class="copyright">
            © 2021 Asociación Argentina de Tartamudez. Todos los derechos reservados. Política de Privacidad. Creado por
            Nahuel Barreiro </span>
          <br />
        
          <br /><br />Telefono: +54 9 11 3277 3093
        </div>



        <div class="column">

          <h1><strong>Enlaces útiles</strong><h1>

          <br />
          <ul>
            
            <li class="mb-2">
              <a href="https://es-la.facebook.com/www.delegacioncordoba/" target="_blank">Delegación Córdoba de la Asociación Argentina
                de Tartamudez</a></li>
            <li class="mb-2"> <a href="https://www.facebook.com/aatdelegacionpatagonica/" target="_blank">Delegación Patagónica de la Asociación
                Argentina de Tartamudez</a></li>
            <li class="mb-2"> <a href="https://www.isastutter.org/" target="_blank">International Stuttering Association</a></li>

            <li class="mb-2"> <a href="https://www.theifa.org/" target="_blank">International Fluency Association</a></li>
          </ul>
        </div>

        <div class="column"> 
        <h1>   <strong>Social</strong></h1>
          <br />
          <ul>
            <li class="mb-2"> <a href="https://twitter.com/disfluencia_arg" target="_blank">Twitter</a>
            <li class="mb-2"> <a href="https://www.facebook.com/www.aat.org.ar" target="_blank">Facebook</a>
            <li class="mb-2"> <a href="https://www.instagram.com/tartamudez/" target="_blank">Instagram</a>
            <li class="mb-2"> <a href="https://www.youtube.com/channel/UC6xWZs49PHYpI8eJ6Sv2C4Q/videos" target="_blank">Youtube</a>
          </ul>
        </div>
        
        <div class="column">
            <h1>   <strong>Prueba nuestra app</strong></h1>
            <a href="https://play.google.com/store/apps/details?id=com.aatapp.dn.aat&pcampaignid=pcampaignidMKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1" target="_blank"><img alt="Disponible en Google Play" src="https://play.google.com/intl/en_us/badges/static/images/badges/es-419_badge_web_generic.png" class=" lazy-loaded" data-src="https://play.google.com/intl/en_us/badges/static/images/badges/es-419_badge_web_generic.png"></a>
            <p>ó</p>
           <a href="http://test.aat.org.ar/" target="_blank" class="button is-success mt-5">Test de tartamudez</a>
            
        </div>




        <div class="column is-two-fifths is-hidden-tablet">
          <span class="copyright">
            © 2021 Asociación Argentina de Tartamudez. Todos los derechos reservados. Política de Privacidad. Creado por
            Nahuel Barreiro </span>
          <br />
          
          <br /><br />Telefono: +54 9 11 3277 3093
        </div>
      </div>
    </div>

  </footer>

</body>

</html>

viewpage/templates/donar.html
{% extends 'base.html' %}

{% block titulo %}
Donar - AAT
{% endblock titulo %}

{% block body %}



<section class="section">
<div class="container">
 <div class="content is-medium">
<strong>DATOS DE LA CUENTA:</strong>
            <p>BANCO NACIÓN</br>
                Asociación Argentina de Tartamudez</br>
                CAJA DE AHORRO (Cuenta especial en pesos)</br>
                Número de cuenta: 130857347</br>
                CBU: 0110013640001308573476</br>
                CUIT: 30-69222582-8</p>

            <p>¡Se parte de una lucha colectiva!</br>
                Muchas gracias</p></div>
            

<div class="column is-half">

<h2 class="title is-4">Además si tenés ganas dejanos un mensaje</h2>

                <form method='post'>
                    {% csrf_token %}
                    <div class="field">
                        <label class="label has-text-left">Nombre</label>
                        <div class="control">
                            {{form.nombre}}
                        </div>
                      </div>
                      
                
                      
                      <div class="field">
                        <label class="label has-text-left">Email</label>
                        <div class="control">
                            {{form.mail}}
                          </span>
                </div>
                </div>
                
                      
                      <div class="field">
                        <label class="label has-text-left">Mensaje</label>
                        <div class="control">
                            {{form.mensaje}}
                        </div>
                      </div>
                      
                      <div class="field">
                      <div class="g-recaptcha" data-sitekey="6LcuBzgaAAAAACeb28NBQLieHIM-YDM64_drzPjM"></div>
                      
                      </div>
                      
                      {% if messages %}
                    {% for message in messages %}
                    
                    <div class="notification {{ message.tags }}">{{ message }}</div>
                    {% endfor %}
                    {% endif %}
                      
                      
                      
                       
                   
                      <div class="field is-grouped">
                        <div class="control">
                          <button class="button is-success is-fullwidth has-text-weight-medium is-medium">Enviar Mensaje</button>
                        </div>
                      </div>
                </form>


            
            </div>
            </div>
</section>
{% endblock body %}

viewpage/templates/socios-suscriptores.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}
Socios y suscriptores - AAT
{% endblock titulo %}


{% block js %}
<script defer src="https://use.fontawesome.com/releases/v5.14.0/js/all.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-extensions@6.2.7/bulma-pricingtable/dist/css/bulma-pricingtable.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>


{% endblock js %}


{% block body %}

<script>
    $(document).ready(function () {
    $("#id_pais").change(function () {
        var val = $(this).val();
        if (val !== "Argentina") {
            $("#id_provincia").hide();
            
        }
        else{
            $("#id_provincia").show();
        }
    });
});
</script>


<section class="section">
    <div class="container">
        <div class="content is-medium">

            <h2 class="title is-3">
                Socios y Suscriptores
            </h2>

            <p>La Asociación Argentina de Tartamudez (A.A.T.) es una Asociación Civil sin fines de lucro (Pers.
                Jurúdica 305/97 – Exp. 1632188/97).</br>
                Tiene como objetivo la investigación, prevención y difusión de todo lo relacionado con la
                tartamudez. Invitamos a papás, profesionales, personas disfluentes a asociarse.</br>

                <strong>
                    <div class="mt-2">Los objetivos de la institución son:</div>
                </strong>


                <li> Desarrollar una intervención precoz trabajando en la prevención</li>

                <li> Aumentar la eficacia de los tratamiento.</li>
                <li> Hacer progresar la investigación sobre la tartamudez y su abordaje.</li>

                <li>Tener una sede propia donde funcione un centro permanente</li></br>

                Todos los días trabajamos incansablemente para poder crecer como Asociación. Queremos incorporar
                más actividades, capacitaciones, beneficios…
                ¡Queremos llegar a todo nuestro país para poder ayudar a más personas!
            </p>

            <strong> Para inscribirte como socio debes:</strong>
            <ol type="1">
                <li>Elegir una opción detallada más abajo.</li>
                <li>Llenar el formulario.</li>
                <li>Enviar el formulario.</li>
                <li>En breve le responderemos.</li>
                <li>Por cualquier consulta comunicarse a info@aat.org.ar</li>

            </ol>

            <strong>La Cuota es ANUAL: </strong>

            <p>– Personas con tartamudez, familiares y público en general: $500</br>
                – Profesionales: $4000</p>



            <strong>DATOS DE LA CUENTA:</strong>
            <p>BANCO NACIÓN</br>
                Asociación Argentina de Tartamudez</br>
                CAJA DE AHORRO (Cuenta especial en pesos)</br>
                Número de cuenta: 130857347</br>
                CBU: 0110013640001308573476</br>
                CUIT: 30-69222582-8</p>

            <p>¡Se parte de una lucha colectiva!</br>
                Muchas gracias</p>




        </div>

        <div class="pricing-table">
            <div class="pricing-plan">
                <div class="plan-header">Suscripción <p class="has-text-weight-light"> Personas que deseen
                        recibir</br> información</p>
                </div>
                <div class="plan-price is-3"><span class="plan-price-currency is-size-5">Gratis</span></div>
                <div class="plan-items">
                    <div class="plan-item">Información de jornadas y eventos </div>
                    <div class="plan-item">-</div>
                    <div class="plan-item">-</div>
                    <div class="plan-item">-</div>
                    <div class="plan-item">-</div>

                </div>
            </div>

            <div class="pricing-plan is-warning">
                <div class="plan-header">Socios <p class="has-text-weight-light"> Personas con tartamudez,</br>
                        familiares y público en general</p>
                </div>
                <div class="plan-price"><span class="plan-price-amount"><span
                            class="plan-price-currency">$</span>500</span>/año</div>
                <div class="plan-items">
                    <div class="plan-item">Información de jornadas y eventos </div>
                    <div class="plan-item"> Acceso a biblioteca virtual </div>
                    <div class="plan-item"> Descuentos en jornadas y eventos </div>
                    <div class="plan-item">-</div>
                    <div class="plan-item">-</div>
                </div>

            </div>

            <div class="pricing-plan is-active">
                <div class="plan-header">Socios <p class="has-text-weight-light">Profesionales</p>
                </div>
                <div class="plan-price"><span class="plan-price-amount"><span
                            class="plan-price-currency">$</span>4000</span>/año</div>
                <div class="plan-items">
                    <div class="plan-item">Información de jornadas y eventos </div>
                    <div class="plan-item"> Acceso a biblioteca virtual </div>
                    <div class="plan-item"> Descuentos en jornadas y eventos </div>
                    <div class="plan-item">Descuentos en cursos y capacitaciones </div>
                    <div class="plan-item">Publicación del profesional en la página </div>
                </div>

            </div>

        </div>
        <section class="section">
            {% comment %} formulario {% endcomment %}
            <form method="POST"> {% csrf_token %}


                    <div class="field">
                           

                        <label class="label">Elige una opción</label>
                        <div class="control">
                            <div class="select">
                                {{ form.Socio_suscriptor }}
                            </div>
                        </div>
                    </div>

                    <div class="field">
                        <label class="label">Nombre</label>
                        <div class="control">
                            {{form.nombre}}
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Apellido</label>
                        <div class="control">
                            {{form.apellido}}
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Correo electrónico</label>
                        <div class="control">
                            {{form.mail}}
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Teléfono</label>
                        <div class="control">
                            {{form.telefono}}
                        </div>
                    </div>

                    <div class="field">
                        <label class="label">País</label>
                        <p class="control has-icons-left">
                            <span class="select">
                            {{form.pais}}
                            </span>
                            <span class="icon is-small is-left">
                                <i class="fas fa-globe"></i>
                            </span>
                        </p>
                    </div>

                    <div class="field">
                        <label class="label">Provincia</label>
                        
                            <span class="select">
                            {{form.provincia}}
                            </span>
                        </p>
                    </div>

                    <div class="field">
                        <label class="label">Lugar de residencia</label>
                        <div class="control">
                            {{form.lugar_de_residencia}}
                        </div>
                    </div>
                    
                    <div class="field">
                        <label class="label">Fecha de Nacimiento</label>
                        <div class="control">
                            {{form.nacimiento}}
                        </div>
                    </div>

                     <div class="field">
                        <label class="label">Tipo de persona</label>
                        
                            <span class="select">
                            {{form.tipo_de_persona}}

                             </span>
                            
                       
                    </div>
                   


                    <div class="field">
                        <label class="label">Mensaje</label>
                        
                            
                       {{form.mensaje}}
                    </div>
                  
                
                
                    


                <div class="field">
                      <div class="g-recaptcha" data-sitekey="6LcuBzgaAAAAACeb28NBQLieHIM-YDM64_drzPjM"></div>
                      
                      </div>
                  {% if messages %}
                    {% for message in messages %}
                    
                    <div class="notification {{ message.tags }}">{{ message }}</div>
                    {% endfor %}
                    {% endif %}


                <input type="submit" class="button is-success" value="Enviar">
            </form>






        </section>


    </div>
    </div>
</section>

<script src="/node_modules/bulma-extensions/bulma-calendar/dist/bulma-calendar.min.js"></script>




{% endblock body %}